import requests
from bs4 import BeautifulSoup


def supports_https(domain_name: str) -> bool:
    """
    Attempts to connect to HTTPS-supporting site.

    Return:
        bool: True, if HTTPS-connection is established. Otherwise, false.
    """
    try:
        requests.head(f"https://{domain_name}",
                                 timeout=5,
                                 allow_redirects=True)
        return True
    except requests.exceptions.SSLError:
        return False
    except requests.exceptions.ReadTimeout:
        return False


def fetch_page_resource(url: str) -> str | None:
    """
    Attempts to obtain a string copy of HTML/CSS code from the given URL.

    Args:
        url: The URL to retrieve HTML/CSS text from.
    
    Returns:
        str: A string of HTML/CSS text. Otherwise, none.
    """
    try:
        resource = requests.get(url, timeout=5, headers={"User-Agent": "PreviewBot/1.0"})
        return resource.text
    except requests.RequestException:
        return None


def fetch_page_resource_soup(url: str) -> BeautifulSoup | None:
    """
    Attempts to obtain BeautifulSoup object from URL.
    """
    try:
        html = fetch_page_resource(url)
        soup = BeautifulSoup(html, 'html.parser')
        return soup
    except requests.RequestException:
        return None


def get_api_key() -> str:
    """
    Safely loads API key if it exists in environment variables.

    Returns:
        str: If API key fetch was successfull. Otherwise, returns None.
    """
    import os

    try:
        from dotenv import load_dotenv
        load_dotenv(".env")
    except ImportError:  # Silently skips if dotenv not installed
        pass

    API_KEY = os.getenv("API_KEY")

    if API_KEY is None:
        raise KeyError('The environment variable "API_KEY" was not found.')
    
    return API_KEY
    

def submit_url_to_virustotal(target_url: str) -> str:
    """
    Submits a URL for scanning to VirusTotal and obtains the link with scan results.

    Args:
        target_url: The URL to be submitted to and scanned by VirusTotal.

    Returns:
        str: The link to the webpage with scan results generated by VirusTotal.
    """
    base_url = f"https://www.virustotal.com/api/v3/urls"

    headers = {
        "x-apikey": get_api_key()
    }

    data = {
        "url": target_url
    }

    response = requests.post(base_url, headers=headers, data=data)
    data = response.json()
    scanned_url_link = data["data"]["links"]["self"]

    return scanned_url_link


def request_url_from_virustotal(target_url: str) -> dict:
    """
    Asks VirusTotal for a response concerning the scanned URL.

    Args:
        target_url: The link to the webpage with results of the previously scanned URL.

    Returns:
        dict: A dictionary object representing the malware statistics for a URL.
    """
    headers = {
        "x-apikey": get_api_key()
    }

    response = requests.get(target_url, headers=headers)
    data = response.json()

    return data["data"]["attributes"]["stats"]


def fetch_virustotal_stats(url: str) -> dict:
    """
    Pipeline for getting statistics on URL analysis by VirusTotal.

    Args:
        url: URL to be submitted to and scanned by VirusTotal.

    Returns:
        dict: A dictionary object representing the malware statistics for a URL.
    """
    processed_url_pg = submit_url_to_virustotal(url)
    stats = request_url_from_virustotal(processed_url_pg)
    return stats
